import { AxiosInstance } from "axios";
import { createDotnetAxiosClient, createJavaAxiosClient, uploadFormDataToDotnet, uploadFormDataToJava } from "./axios.client";
import { setupAuthRequestInterceptor, setupDotnetAuthResponseInterceptor, setupJavaErrorResponseInterceptor } from "./interceptors";
const axiosDotnet: AxiosInstance = createDotnetAxiosClient();
setupAuthRequestInterceptor(axiosDotnet);
setupDotnetAuthResponseInterceptor(axiosDotnet);
const axiosJava: AxiosInstance = createJavaAxiosClient();
setupAuthRequestInterceptor(axiosJava);
setupJavaErrorResponseInterceptor(axiosJava);
export const axiosDotnetFormData = uploadFormDataToDotnet;
export const axiosJavaFormData = uploadFormDataToJava;
export { axiosDotnet, axiosJava };
export default axiosDotnet;